doc modification
intel/confidential-computing-zoo pull request #55
Opened 2022-04-25 08:02 UTC by Hsy-Intel

## Description of the PR 

## How to test this PR?

2022-04-28 06:37 UTC, RodgerZhu commented on cczoo/horizontal_fl/README.md
> +
Under public cloud, is <PCCS ip addr> sitll needed? Or can it be ignored as below?
./start_container.sh worker1

2022-04-28 06:37 UTC, RodgerZhu commented on cczoo/horizontal_fl/hfl-tensorflow/python.manifest.template
>  sgx.remote_attestation = true
sgx.remote_attestation = true
can be removed.

2022-04-28 06:37 UTC, RodgerZhu commented on cczoo/horizontal_fl/hfl-tensorflow/python.manifest.template
>  sgx.protected_files_key = "ffeeddccbbaa99887766554433221100"
sgx.protected_files_key = "ffeeddccbbaa99887766554433221100"
can be removed.

2022-04-29 02:21 UTC, yuanwu2017 requested changes
The title is too simple. It should be "Refine the readme for training log and model saving information"

2022-05-09 00:22 UTC, RodgerZhu approved these changes

2022-05-09 05:39 UTC, yuanwu2017 approved these changes

2022-05-09 06:11 UTC, merged